### ISSUE TITLE
About Runtime

### ISSUE THREAD

**Issue by foxkw** [InhwanBae/ENet-SAD_Pytorch#10]
In the Paper, it can reach 13.4ms on titan X, but why your code is 16ms on 2080ti, shouldn’t it be faster?  Hope to answer it, thank you very much

**Comment by InhwanBae** [comment]
Hi @foxkw 

Thanks for your interest in my implementation. The reason for the different inference times may be due to various causes. First, the official code and my implementation were written in different languages. Additionally, using [PyTorch APEX](https://nvidia.github.io/apex/), or designing the image pre- and post-processing as a pipeline, the execution speed can be much faster.

I hope this answers your questions.

**Comment by InhwanBae** [comment]
Thank you for your interest. I'm closing this issue for now. Please feel free to open another issue for other questions.
